# Imports

In [2]:
import pandas as pd

In [3]:
raw_data = pd.read_csv('Absenteeism_data.csv')

df = raw_data.copy()
df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         700 non-null    int64
 1   Reason for Absence         700 non-null    int64
 2   Date                       700 non-null    str
 3   Transportation Expense     700 non-null    int64
 4   Distance to Work           700 non-null    int64
 5   Age                        700 non-null    int64
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64
 8   Education                  700 non-null    int64
 9   Children                   700 non-null    int64
 10  Pets                       700 non-null    int64
 11  Absenteeism Time in Hours  700 non-null    int64
dtypes: float64(1), int64(10), str(1)
memory usage: 72.6 KB

In [5]:
reason_dummies = pd.get_dummies(df['Reason for Absence'],drop_first=True,dtype=int)
reason_dummies['Sum']= reason_dummies.sum(axis=1)
reason_dummies['Sum'].unique()

array([1, 0])

## Splitting Reasons into 4 groups

In [6]:
reason_type1 = reason_dummies.loc[:,:14].max(axis=1)
reason_type2 = reason_dummies.loc[:,15:17].max(axis=1)
reason_type3 = reason_dummies.loc[:,18:21].max(axis=1)
reason_type4 = reason_dummies.loc[:,22:].max(axis=1)

In [7]:
df = df.drop(['ID','Reason for Absence'],axis=1)
df.head()

,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,23/07/2015,289,36,33,239.554,30,1,2,1,2

In [8]:
df = pd.concat([df,reason_type1,reason_type2,reason_type3,reason_type4],axis=1)

In [9]:
df.columns = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2','Reason_3' ,'Reason_4']

In [10]:
col_order = [ 'Reason_1', 'Reason_2','Reason_3' ,'Reason_4',
       'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

df = df[col_order]

df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,1,0,0,1,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,23/07/2015,289,36,33,239.554,30,1,2,1,2

## Checkpoint

In [11]:
df_checkpoint = df.copy()

In [12]:
df['Date'] = pd.to_datetime(df['Date'],format='%d/%m/%Y')

type(df['Date'][0])

pandas.Timestamp

In [13]:
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2
3,1,0,0,1,2015-07-16,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2

In [14]:
list_month=[]

In [15]:
for i in range(df.shape[0]):
    list_month.append(df['Date'][i].month)

In [16]:
df['Month'] = list_month

In [17]:
def get_day(date_value):
    return date_value.weekday()

df['Day'] = df['Date'].apply(get_day)

In [18]:
df.head(20)

,Reason_1,Reason_2,Reason_3,Reason_4,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Day
0,0,0,0,1,2015-07-07,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,2015-07-14,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,1,2015-07-16,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,2015-07-23,289,36,33,239.554,30,1,2,1,2,7,3
5,0,0,0,1,2015-07-10,179,51,38,239.554,31,1,0,0,2,7,4
6,0,0,0,1,2015-07-17,361,52,28,239.554,27,1,1,4,8,7,4
7,0,0,0,1,2015-07-24,260,50,36,239.554,23,1,4,0,4,7,4
8,0,0,1,1,2015-07-06,155,12,34,239.554,25,1,2,0,40,7,0
9,0,0,0,1,2015-07-13,235,11,37,239.554,29,3,1,1,8,7,0
10,1,0,0,1,2015-07-20,260,50,36,239.554,23,1,4,0,8,7,0
11,1,0,0,1,2015-07-14,260,50,36,239.554,23,1,4,0,8,7,1
12,1,0,0,1,2015-07-15,260,50,36,239.554,23,1,4,0,8,7,2
13,1,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,1,7,2
14,0,0,0,1,2015-07-15,179,51,38,239.554,31,1,0,0,4,7,2
15,1,0,0,1,2015-07-17,246,25,41,239.554,23,1,0,0,8,7,4
16,0,0,0,1,2015-07-17,179,51,38,239.554,31,1,0,0,2,7,4
17,0,0,1,1,2015-07-27,179,51,38,239.554,31,1,0,0,8,7,0
18,1,0,0,1,2015-07-30,189,29,33,239.554,25,1,2,2,8,7,3
19,0,0,0,1,2015-08-05,248,25,47,205.917,32,1,2,1,2,8,2

In [19]:
df = df.drop(['Date'],axis=1)

In [20]:

df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Month,Day
0,0,0,0,1,289,36,33,239.554,30,1,2,1,4,7,1
1,0,0,0,0,118,13,50,239.554,31,1,1,0,0,7,1
2,0,0,0,1,179,51,38,239.554,31,1,0,0,2,7,2
3,1,0,0,1,279,5,39,239.554,24,1,2,0,4,7,3
4,0,0,0,1,289,36,33,239.554,30,1,2,1,2,7,3

In [21]:
col_order = [                 'Reason_1',                  'Reason_2',
                  'Reason_3',                  'Reason_4',                     'Month',
                       'Day',
    'Transportation Expense',          'Distance to Work',
                       'Age',   'Daily Work Load Average',
           'Body Mass Index',                 'Education',
                  'Children',                      'Pets',
 'Absenteeism Time in Hours']

In [22]:
df = df[col_order]

In [23]:
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,1,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,1,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,1,0,0,2
3,1,0,0,1,7,3,279,5,39,239.554,24,1,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,1,2,1,2

In [24]:
df['Education'] = df['Education'].map({1:0,2:1,3:1,4:1})

## Final Checkpoint

In [25]:
df_preprocessed = df.copy()

In [26]:
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

In [27]:
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False)