# Imports

In [263]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from  sklearn import metrics

# Data

In [264]:
df = pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

## Set target

In [265]:
targets = np.where(df['Absenteeism Time in Hours']<=np.median(df['Absenteeism Time in Hours']),0,1)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [266]:
df['Excessive Absenteeism'] = targets
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

### Checkpoint

In [267]:
df_with_targets = df.drop(
    ['Absenteeism Time in Hours',
     'Day',
     'Daily Work Load Average',
     'Distance to Work'],
    axis=1
)

In [268]:
df_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,1,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

## Input

In [269]:
unscaled_inputs = df_with_targets.iloc[:,:-1]

In [270]:
unscaled_inputs.columns.values

<ArrowStringArray>
[              'Reason_1',               'Reason_2',               'Reason_3',
               'Reason_4',                  'Month', 'Transportation Expense',
                    'Age',        'Body Mass Index',              'Education',
               'Children',                   'Pets']
Length: 11, dtype: str

# Standardization

In [271]:

absenteeism_scaler = StandardScaler()

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler



class CustomScaler(BaseEstimator,TransformerMixin):


    def __init__(self,columns,copy=True,with_mean=True,with_std=True):


        self.scaler = StandardScaler(copy=copy,
                                     with_mean=with_mean,
                                     with_std=with_std)

        self.columns = columns
        self.mean_ = None
        self.var_ = None




    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self



    def transform(self, X, y=None, copy=None):


        init_col_order = X.columns


        x_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)


        x_not_scaled = X.loc[:,~X.columns.isin(self.columns)]


        return pd.concat([x_not_scaled, x_scaled], axis=1)[init_col_order]

In [272]:

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [273]:
absenteeism_scaler = CustomScaler(columns_to_scale)

absenteeism_scaler.fit(unscaled_inputs)

scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

# Train Test Split

In [274]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,test_size=0.2,random_state=20)

# Model

In [275]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [276]:
model.score(x_train,y_train)*100

78.75

# Summary

In [277]:
model.intercept_

array([-3.21683108])

In [278]:
model.coef_

array([[ 1.98238129,  0.49528992,  2.37877814,  2.45317221,  0.17998465,
         0.66250801, -0.17799445,  0.30628123, -0.24506209,  0.37075429,
        -0.30195521]])

In [279]:
feature_name = unscaled_inputs.columns.values

In [280]:
summary = pd.DataFrame(columns=['feature name'],data = feature_name)

In [281]:
summary['Coeficients'] = np.transpose(model.coef_)

In [282]:
summary.index = summary.index+1

In [283]:
summary.loc[0] = ['Intercept',model.intercept_[0]]
summary = summary.sort_index()

In [284]:
summary

              feature name  Coeficients
0                Intercept    -3.216831
1                 Reason_1     1.982381
2                 Reason_2     0.495290
3                 Reason_3     2.378778
4                 Reason_4     2.453172
5                    Month     0.179985
6   Transportation Expense     0.662508
7                      Age    -0.177994
8          Body Mass Index     0.306281
9                Education    -0.245062
10                Children     0.370754
11                    Pets    -0.301955

In [285]:
summary['Odds Ratio'] = np.exp(summary['Coeficients'])

In [286]:
pd.options.display.max_rows=None
display(summary.sort_values('Odds Ratio',ascending = False))

              feature name  Coeficients  Odds Ratio
4                 Reason_4     2.453172   11.625166
3                 Reason_3     2.378778   10.791709
1                 Reason_1     1.982381    7.260011
6   Transportation Expense     0.662508    1.939651
2                 Reason_2     0.495290    1.640974
10                Children     0.370754    1.448827
8          Body Mass Index     0.306281    1.358364
5                    Month     0.179985    1.197199
7                      Age    -0.177994    0.836947
9                Education    -0.245062    0.782656
11                    Pets    -0.301955    0.739371
0                Intercept    -3.216831    0.040082

In [290]:
model.score(x_test,y_test)*100

73.57142857142858

## Module

In [287]:
import pickle

In [289]:
with open('model','wb') as file:
    pickle.dump(model,file)

with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)