# Imports

In [137]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from  sklearn import metrics

# Data

In [138]:
df = pd.read_csv('Absenteeism_preprocessed.csv')
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2

## Set target

In [139]:
targets = np.where(df['Absenteeism Time in Hours']<=np.median(df['Absenteeism Time in Hours']),0,1)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [140]:
df['Excessive Absenteeism'] = targets
df.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0

### Checkpoint

In [141]:
df_with_targets = df.drop(['Absenteeism Time in Hours'],axis=1)

In [142]:
df_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month,Day,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,0
3,1,0,0,1,7,3,279,5,39,239.554,24,0,2,0,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,0

## Input

In [143]:
unscaled_inputs = df_with_targets.iloc[:,:-1]

# Standardization

In [144]:
columns_to_scale = ['Month',                     'Day',
  'Transportation Expense',        'Distance to Work',
                     'Age', 'Daily Work Load Average',
         'Body Mass Index',               'Education',
                'Children',                    'Pets']

In [158]:

Absenteeism_scaler = ColumnTransformer(transformers=[('scaler',StandardScaler(),columns_to_scale)],remainder='passthrough')

scaled_inputs = Absenteeism_scaler.fit_transform(unscaled_inputs)

scaled_inputs

array([[ 0.18272635, -0.68370352,  1.00584437, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.18272635, -0.68370352, -1.57468098, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.18272635, -0.00772546, -0.6541427 , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-0.3882935 ,  0.66825259,  1.62456682, ...,  0.        ,
         0.        ,  1.        ],
       [-0.3882935 ,  0.66825259,  0.19094163, ...,  0.        ,
         0.        ,  1.        ],
       [-0.3882935 ,  0.66825259,  1.03602595, ...,  0.        ,
         0.        ,  1.        ]], shape=(700, 14))

# Train Test Split

In [146]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,targets,test_size=0.2,random_state=20)

# Model

In [147]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [148]:
model.score(x_train,y_train)*100

78.75

# Summary

In [149]:
model.intercept_

array([-3.27590026])

In [150]:
model.coef_

array([[ 0.18630269, -0.08445469,  0.67887094, -0.0373627 , -0.17993402,
         0.00838709,  0.29906758, -0.10458289,  0.38325207, -0.3115161 ,
         1.96245171,  0.47179244,  2.34153265,  2.48312399]])

In [151]:
feature_name = unscaled_inputs.columns.values

In [152]:
summary = pd.DataFrame(columns=['feature name'],data = feature_name)

In [153]:
summary['Coeficients'] = np.transpose(model.coef_)

In [154]:
summary.index = summary.index+1

In [156]:
summary.loc[0] = ['Intercept',model.intercept_[0]]
summary = summary.sort_index()

In [157]:
summary

               feature name  Coeficients
0                 Intercept    -3.275900
1                  Reason_1     0.186303
2                  Reason_2    -0.084455
3                  Reason_3     0.678871
4                  Reason_4    -0.037363
5                     Month    -0.179934
6                       Day     0.008387
7    Transportation Expense     0.299068
8          Distance to Work    -0.104583
9                       Age     0.383252
10  Daily Work Load Average    -0.311516
11          Body Mass Index     1.962452
12                Education     0.471792
13                 Children     2.341533
14                     Pets     2.483124

In [159]:
summary['Odds Ratio'] = np.exp(summary['Coeficients'])

In [168]:
summary.sort_values('Odds Ratio',ascending = False)

               feature name  Coeficients  Odds Ratio
14                     Pets     2.483124   11.978627
13                 Children     2.341533   10.397160
11          Body Mass Index     1.962452    7.116754
3                  Reason_3     0.678871    1.971650
12                Education     0.471792    1.602865
9                       Age     0.383252    1.467048
7    Transportation Expense     0.299068    1.348601
1                  Reason_1     0.186303    1.204787
6                       Day     0.008387    1.008422
4                  Reason_4    -0.037363    0.963327
2                  Reason_2    -0.084455    0.919013
8          Distance to Work    -0.104583    0.900700
5                     Month    -0.179934    0.835325
10  Daily Work Load Average    -0.311516    0.732336
0                 Intercept    -3.275900    0.037783