In [15]:
 from basic_imports import *

In [16]:
file_path = "Walmart_Sales.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "mikhail1681/walmart-sales",
  file_path,
)

df.head()

C:\Users\sankp\AppData\Local\Temp\ipykernel_35172\344007678.py:3: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [17]:
df.drop_duplicates()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106
...,...,...,...,...,...,...,...,...
6430,45,28-09-2012,713173.95,0,64.88,3.997,192.013558,8.684
6431,45,05-10-2012,733455.07,0,64.89,3.985,192.170412,8.667
6432,45,12-10-2012,734464.36,0,54.47,4.000,192.327265,8.667
6433,45,19-10-2012,718125.53,0,56.47,3.969,192.330854,8.667
6434,45,26-10-2012,760281.43,0,58.85,3.882,192.308899,8.667

In [18]:
df['Date'] = pd.to_datetime(df['Date'],format="%d-%m-%Y")

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

df.drop('Date',axis=1, inplace=True)

In [19]:
df= df[['Year', 'Month', 'Day' ,'Store', 'Holiday_Flag', 'Temperature', 'Fuel_Price', 'CPI', 'Unemployment', 'Weekly_Sales']]

In [20]:
df.head()

,Year,Month,Day,Store,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Weekly_Sales
0,2010,2,5,1,0,42.31,2.572,211.096358,8.106,1643690.90
1,2010,2,12,1,1,38.51,2.548,211.242170,8.106,1641957.44
2,2010,2,19,1,0,39.93,2.514,211.289143,8.106,1611968.17
3,2010,2,26,1,0,46.63,2.561,211.319643,8.106,1409727.59
4,2010,3,5,1,0,46.50,2.625,211.350143,8.106,1554806.68